version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - proxybackend

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
    build:
      context: .
      dockerfile: Gateway/Gateway.Api/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:8080"
    networks: 
       - proxybackend

  core.db:
    container_name: core.db
    image: postgres:14.5-alpine
    volumes:
      - ./Services/CoreService.Api/init-db/:/docker-entrypoint-initdb.d
      - ./Services/CoreService.Api/pg-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: 
       - proxybackend

  core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENVIRONMENT=Docker
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      dockerfile: Services/CoreService.Api/Dockerfile
    volumes:
      - './:/core'
    ports:
      - "5001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      core.db:
        condition: service_healthy
    networks: 
       - proxybackend

  auth.db:
    container_name: auth.db
    image: postgres:14.5-alpine
    volumes:
      - ./Services/AuthService.Api/pg-data:/var/lib/postgresql/data
    ports:
      - "1435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: 
       - proxybackend

  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENVIRONMENT=Docker
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      dockerfile: Services/AuthService.Api/Dockerfile
    volumes:
      - './:/auth'
    ports:
      - "5002:8080"
    depends_on:
      auth.db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks: 
       - proxybackend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

networks:
  proxybackend:
    name: proxybackend
    driver: bridge
