<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>PracticeEntities</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.0-preview" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.0-preview" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5"/>
        <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.1.2" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.1.2" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.2" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="..\..\stylecop.json" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
