// <auto-generated />
using System;
using CoreService.Api.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreService.Api.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20260704044613_AddedEmailField")]
    partial class AddedEmailField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreService.Api.Core.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contact");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middlename");

                    b.Property<string>("Userid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("consultants_pkey");

                    b.ToTable("consultants", (string)null);
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("program");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("groups_pkey");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cansupervisevkr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cansupervisevkr");

                    b.Property<string>("Department")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middlename");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("lecturers_pkey");

                    b.ToTable("lecturers", (string)null);
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Consultantid")
                        .HasColumnType("integer")
                        .HasColumnName("consultantid");

                    b.Property<DateTime>("Createddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Finalgrade")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("finalgrade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<int>("Supervisorid")
                        .HasColumnType("integer")
                        .HasColumnName("supervisorid");

                    b.Property<int>("Themeid")
                        .HasColumnType("integer")
                        .HasColumnName("themeid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.Property<DateTime>("Updateddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updateddate")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("practices_pkey");

                    b.HasIndex("Consultantid");

                    b.HasIndex("Studentid");

                    b.HasIndex("Supervisorid");

                    b.HasIndex("Themeid");

                    b.ToTable("practices", (string)null);
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<int?>("Groupid")
                        .HasColumnType("integer")
                        .HasColumnName("groupid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middlename");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("students_pkey");

                    b.HasIndex("Groupid");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Consultantid")
                        .HasColumnType("integer")
                        .HasColumnName("consultantid");

                    b.Property<DateTime>("Createddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Department")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<bool>("Isarchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isarchived");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("level");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<string>("Suggestedby")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("suggestedby");

                    b.Property<int?>("Supervisorid")
                        .HasColumnType("integer")
                        .HasColumnName("supervisorid");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("Updateddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updateddate")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("themes_pkey");

                    b.HasIndex("Consultantid");

                    b.HasIndex("Supervisorid");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Practice", b =>
                {
                    b.HasOne("CoreService.Api.Core.Models.Consultant", "Consultant")
                        .WithMany("Practices")
                        .HasForeignKey("Consultantid")
                        .HasConstraintName("consultant_fk");

                    b.HasOne("CoreService.Api.Core.Models.Student", "Student")
                        .WithMany("Practices")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("student_fk");

                    b.HasOne("CoreService.Api.Core.Models.Lecturer", "Supervisor")
                        .WithMany("Practices")
                        .HasForeignKey("Supervisorid")
                        .IsRequired()
                        .HasConstraintName("supervisor_fk");

                    b.HasOne("CoreService.Api.Core.Models.Theme", "Theme")
                        .WithMany("Practices")
                        .HasForeignKey("Themeid")
                        .IsRequired()
                        .HasConstraintName("theme_fk");

                    b.Navigation("Consultant");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Student", b =>
                {
                    b.HasOne("CoreService.Api.Core.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("Groupid")
                        .HasConstraintName("group_fk");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Theme", b =>
                {
                    b.HasOne("CoreService.Api.Core.Models.Consultant", "Consultant")
                        .WithMany("Themes")
                        .HasForeignKey("Consultantid")
                        .HasConstraintName("consultant_fk");

                    b.HasOne("CoreService.Api.Core.Models.Lecturer", "Supervisor")
                        .WithMany("Themes")
                        .HasForeignKey("Supervisorid")
                        .HasConstraintName("lecturer_fk");

                    b.Navigation("Consultant");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Consultant", b =>
                {
                    b.Navigation("Practices");

                    b.Navigation("Themes");
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Lecturer", b =>
                {
                    b.Navigation("Practices");

                    b.Navigation("Themes");
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Student", b =>
                {
                    b.Navigation("Practices");
                });

            modelBuilder.Entity("CoreService.Api.Core.Models.Theme", b =>
                {
                    b.Navigation("Practices");
                });
#pragma warning restore 612, 618
        }
    }
}
