FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Services/AuditService.Api/AuditService.Api.csproj", "Services/AuditService.Api/"]
RUN dotnet restore "Services/AuditService.Api/AuditService.Api.csproj"
COPY . .
WORKDIR "/src/Services/AuditService.Api"
RUN dotnet build "./AuditService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./AuditService.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AuditService.Api.dll"]