name: C# CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build PracticesService.sln

      - name: Tests
        run: dotnet test PracticesService.sln

      - name: Dotnet format 
        run: dotnet format PracticesService.sln